use_frameworks!

platform :ios, '9.0'

target 'NanoModule_Example' do
  pod 'NanoModule', :path => '../'

  target 'NanoModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
